#!/usr/bin/env bash

echo "Welcome, "$USER" to the Set up..."
echo "This will install some useful apps, and set some basic osx settings"
echo "First up, lets install all the things!"
read

### Homebrew installs

brew bundle
brew install vim --override-system-vi

read
echo "Full disclosure.... we installed vim."
echo ".........."
read
echo "But don't panic, we also included some basic sane vim setings"
echo "in case you ever get stuck there"
echo "Make a note, your leader key is the space bar, feel free to look at the vimrc for more info"
echo "Press any key to continue"
read

### RVM

echo "Installing RVM"
read

\curl -sSL https://get.rvm.io | bash -s stable --ruby


### Install oh-my-zsh

echo "Installing oh-my-zsh for zsh"
read
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
echo "oh-my-zsh installed!"
echo "Head here to pick a theme"
echo "https://github.com/robbyrussell/oh-my-zsh"

echo "press any key to continue"
read

### Text Editor

text_editor_choice() {
echo "Tell me, which text editor you would like to use?"
read editor

if [ "$editor" == "emacs" ]
then
  echo "Come on, be serious."
  text_editor_choice
fi

if [ "$editor" == "vim" ]
then
  echo "Great choice, and it's already installed. Double win."
fi

if [ "$editor" == "atom" ]
then
	echo "Good choice"
  brew cask install --appdir="/Applications" atom
fi

if [ "$editor" == "sublime" ]
then
	echo "Good choice"
  brew cask install --appdir="/Applications" sublime-text
fi

if [ "$editor" != "atom" ] || [ "$editor" != "sublime" ] || [ "$editor" != "vim" ]
then
  echo "Tough you are getting sublime"
  brew cask install --appdir="/Applications" sublime-text
fi
}

text_editor_choice

### OSX Defaults

sh make_osx_great_again

# Dock Apps

sh reset_dock_apps

### git setup

sh git_setup

### SSH keys

sh ssh_keys

### Symlinks...

sh symlinks

echo "... Set up complete!"
echo "One brand spanking new laptop ready for development."
echo "Go get 'em tiger."
read
