#!/usr/bin/env bash

echo "Welcome, "$USER" to the Set up..."
echo "This will install some useful apps, and set some basic osx settings"
echo "First up, lets install all the things!"


### Homebrew installs

brew bundle

touch ~/.vimrc

echo "Full disclosure.... we installed vim."
echo ".........."
echo "But don't panic, we also included some basic sane vim setings"
echo "in case you ever get stuck there"
echo "Make a note, your leader key is the space bar, feel free to look at the vimrc for more info"
echo "Press any key to continue"
read

### Install oh-my-zsh

echo "Installing oh-my-zsh for zsh"
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
echo "oh-my-zsh installed!"
echo "Head here to pick a theme"
echo "https://github.com/robbyrussell/oh-my-zsh"

echo "press any key to continue"
read

### Text Editor

text_editor_choice() {
echo "Tell me, which text editor you would like to use?"
read editor

if [ "$editor" == "emacs" ]
then
  echo "Come on, be serious."
  text_editor_choice
fi

if [ "$editor" == "vim"]
then
  echo "Great choice, and it's already installed. Double win."
fi

if [ "$editor" == "atom" ]
then
	echo "Good choice"
  brew cask install --appdir="/Applications" atom
fi

if [ "$editor" == "sublime" ]
then
	echo "Good choice"
  brew cask install --appdir="/Applications" sublime-text
fi

if [ "$editor" != "atom" ] || [ "$editor" != "sublime" ]
then
  echo "Tough you are getting sublime"
  brew cask install --appdir="/Applications" sublime-text
fi
}

text_editor_choice

### OSX Defaults

echo "Setting up some good OSX defaults"
sh make_osx_great_again
echo "Reseting the dock apps"
sh reset_dock_apps

### git setup

echo "Boom."
echo "Let's setup git.."
echo "Which name do you want to use for git?"
read gitusername
echo "What email do you want to use for git?"
read gitemail
git config --global user.name "$gitusername"
git config --global user.email "$gitemail"
git config --global core.excludesfile '~/the_setup/Dotfiles/.gitignore_global'


### SSH keys

echo "Now lets setup SSH keys for github etc"
echo "tell us the email address you use with github:"
read githubemail
echo "When you're prompted to 'Enter a file in which to save the key,' press Enter. This accepts the default file location."
ssh-keygen -t rsa -b 4096 -C "$githubemail"
echo "Ensuring ssh-agent is enabled:"
eval "$(ssh-agent -s)"
echo "Adding your SSH key to the ssh-agent"
ssh-add ~/.ssh/id_rsa
pbcopy < ~/.ssh/id_rsa.pub
echo "SSH key is copied to clipboard, head to github to add it to your account"
echo "see here for more details"
echo "https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/"

### Symlinks...

sh symlinks

echo "... Set up complete!"
echo "One brand spanking new laptop ready for development."
echo "Go get 'em tiger."
